### ISSUE TITLE
3d printing files

### ISSUE THREAD

**Issue by vitormhenrique** [adammck/hexapod#1]
Hello, Could you share the cad files for this hexapod?

**Comment by adammck** [comment]
They are in adammck/hexapod-parts, or something like that. Maybe a bit out of date.

**Comment by vitormhenrique** [comment]
but do you still have the cad designs? step files? :)

**Comment by adammck** [comment]
Sure. It was designed in SketchUp: [HexapodTwo.zip](https://github.com/adammck/hexapod/files/2453955/HexapodTwo.zip)

**Comment by TheArchitectEngineer** [comment]
Hi, 

Is it possible to import SketchUp files on SolidWorks ?

**Comment by adammck** [comment]
I don't know, I've never used SolidWorks. It appears that you can export them from SketchUp in a format suitable for import into SolidWorks, but I haven't tried it. (I must emphasize once again that these parts are not suitable for any purpose.)
